version: '3.8'

services:
  # api:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - redis
  # worker:
  #   build: .
  #   command: celery -A src.libs.prompt.celery_app worker --loglevel=info
  #   depends_on:
  #     - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  # scheduler:
  #   build: .
  #   command: celery -A src.libs.tasks beat --loglevel=info
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis
